/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* MW */
#define MW_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define MW_0_INBUF_ENABLED 0u
#define MW_0_INIT_DRIVESTATE 0u
#define MW_0_INIT_MUXSEL 0u
#define MW_0_INPUT_SYNC 2u
#define MW_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define MW_0_NUM 4u
#define MW_0_PORT GPIO_PRT9
#define MW_0_SLEWRATE CY_GPIO_SLEW_FAST
#define MW_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define MW_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define MW_INBUF_ENABLED 0u
#define MW_INIT_DRIVESTATE 0u
#define MW_INIT_MUXSEL 0u
#define MW_INPUT_SYNC 2u
#define MW_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define MW_NUM 4u
#define MW_PORT GPIO_PRT9
#define MW_SLEWRATE CY_GPIO_SLEW_FAST
#define MW_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* WS */
#define WS_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define WS_0_INBUF_ENABLED 0u
#define WS_0_INIT_DRIVESTATE 0u
#define WS_0_INIT_MUXSEL 0u
#define WS_0_INPUT_SYNC 2u
#define WS_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define WS_0_NUM 5u
#define WS_0_PORT GPIO_PRT9
#define WS_0_SLEWRATE CY_GPIO_SLEW_FAST
#define WS_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define WS_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define WS_INBUF_ENABLED 0u
#define WS_INIT_DRIVESTATE 0u
#define WS_INIT_MUXSEL 0u
#define WS_INPUT_SYNC 2u
#define WS_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define WS_NUM 5u
#define WS_PORT GPIO_PRT9
#define WS_SLEWRATE CY_GPIO_SLEW_FAST
#define WS_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SCL */
#define SCL_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define SCL_0_INBUF_ENABLED 1u
#define SCL_0_INIT_DRIVESTATE 1u
#define SCL_0_INIT_MUXSEL 19u
#define SCL_0_INPUT_SYNC 2u
#define SCL_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SCL_0_NUM 4u
#define SCL_0_PORT GPIO_PRT6
#define SCL_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SCL_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SCL_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define SCL_INBUF_ENABLED 1u
#define SCL_INIT_DRIVESTATE 1u
#define SCL_INIT_MUXSEL 19u
#define SCL_INPUT_SYNC 2u
#define SCL_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SCL_NUM 4u
#define SCL_PORT GPIO_PRT6
#define SCL_SLEWRATE CY_GPIO_SLEW_FAST
#define SCL_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SDA */
#define SDA_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define SDA_0_INBUF_ENABLED 1u
#define SDA_0_INIT_DRIVESTATE 1u
#define SDA_0_INIT_MUXSEL 19u
#define SDA_0_INPUT_SYNC 2u
#define SDA_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDA_0_NUM 5u
#define SDA_0_PORT GPIO_PRT6
#define SDA_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SDA_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SDA_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define SDA_INBUF_ENABLED 1u
#define SDA_INIT_DRIVESTATE 1u
#define SDA_INIT_MUXSEL 19u
#define SDA_INPUT_SYNC 2u
#define SDA_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDA_NUM 5u
#define SDA_PORT GPIO_PRT6
#define SDA_SLEWRATE CY_GPIO_SLEW_FAST
#define SDA_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* VWS */
#define VWS_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define VWS_0_INBUF_ENABLED 0u
#define VWS_0_INIT_DRIVESTATE 1u
#define VWS_0_INIT_MUXSEL 0u
#define VWS_0_INPUT_SYNC 2u
#define VWS_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VWS_0_NUM 4u
#define VWS_0_PORT GPIO_PRT10
#define VWS_0_SLEWRATE CY_GPIO_SLEW_FAST
#define VWS_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define VWS_DRIVEMODE CY_GPIO_DM_ANALOG
#define VWS_INBUF_ENABLED 0u
#define VWS_INIT_DRIVESTATE 1u
#define VWS_INIT_MUXSEL 0u
#define VWS_INPUT_SYNC 2u
#define VWS_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VWS_NUM 4u
#define VWS_PORT GPIO_PRT10
#define VWS_SLEWRATE CY_GPIO_SLEW_FAST
#define VWS_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Button */
#define Button_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_0_INBUF_ENABLED 1u
#define Button_0_INIT_DRIVESTATE 0u
#define Button_0_INIT_MUXSEL 0u
#define Button_0_INPUT_SYNC 2u
#define Button_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_0_NUM 4u
#define Button_0_PORT GPIO_PRT0
#define Button_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Button_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_INBUF_ENABLED 1u
#define Button_INIT_DRIVESTATE 0u
#define Button_INIT_MUXSEL 0u
#define Button_INPUT_SYNC 2u
#define Button_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_NUM 4u
#define Button_PORT GPIO_PRT0
#define Button_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* VMudWatt */
#define VMudWatt_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define VMudWatt_0_INBUF_ENABLED 0u
#define VMudWatt_0_INIT_DRIVESTATE 1u
#define VMudWatt_0_INIT_MUXSEL 0u
#define VMudWatt_0_INPUT_SYNC 2u
#define VMudWatt_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VMudWatt_0_NUM 6u
#define VMudWatt_0_PORT GPIO_PRT10
#define VMudWatt_0_SLEWRATE CY_GPIO_SLEW_FAST
#define VMudWatt_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define VMudWatt_DRIVEMODE CY_GPIO_DM_ANALOG
#define VMudWatt_INBUF_ENABLED 0u
#define VMudWatt_INIT_DRIVESTATE 1u
#define VMudWatt_INIT_MUXSEL 0u
#define VMudWatt_INPUT_SYNC 2u
#define VMudWatt_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VMudWatt_NUM 6u
#define VMudWatt_PORT GPIO_PRT10
#define VMudWatt_SLEWRATE CY_GPIO_SLEW_FAST
#define VMudWatt_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* VWheatStone */
#define VWheatStone_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define VWheatStone_0_INBUF_ENABLED 0u
#define VWheatStone_0_INIT_DRIVESTATE 1u
#define VWheatStone_0_INIT_MUXSEL 0u
#define VWheatStone_0_INPUT_SYNC 2u
#define VWheatStone_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VWheatStone_0_NUM 5u
#define VWheatStone_0_PORT GPIO_PRT10
#define VWheatStone_0_SLEWRATE CY_GPIO_SLEW_FAST
#define VWheatStone_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define VWheatStone_DRIVEMODE CY_GPIO_DM_ANALOG
#define VWheatStone_INBUF_ENABLED 0u
#define VWheatStone_INIT_DRIVESTATE 1u
#define VWheatStone_INIT_MUXSEL 0u
#define VWheatStone_INPUT_SYNC 2u
#define VWheatStone_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VWheatStone_NUM 5u
#define VWheatStone_PORT GPIO_PRT10
#define VWheatStone_SLEWRATE CY_GPIO_SLEW_FAST
#define VWheatStone_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
